// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

export const isDemoMode = !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY;

if (isDemoMode) {
  console.warn('GymFlow: Supabase environment variables are missing. Running in demo mode.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || 'https://demo-gymflow.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'demo-anon-key',
  {
    auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    }
  }
);
